#!/bin/bash

# Check if the script is being run as root
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root."
   exit 1
fi


echo AAA info giver

echo wip
echo find files

find / -iname "*.mp3" -print
find /users -iname "*.jpeg" -print
find /users -iname "*.png" -print

echo services

systemctl list-units --type=service --state=active

echo users/groups
compgen -u
