#!/bin/bash

# Check if the script is being run as root
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root."
   exit 1
fi

echo "this script is for mint only run on mint linux or it might brick it; press Ctrl+C to cancel."
sleep 5  # Pauses for 5 seconds
echo "Continuing script..."

