#!/bin/bash
# RSR stands for RSR Software Remover
# Ensure the script is being run as root

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root."
   exit 1
fi
echo read read me 

# wire shark 
echo do you want to remove wire shark? Y/N
read YN

if [ "$YN" = "y" ]; then 
  echo removing wire shark
   sudo apt-get remove --purge wireshark
   sudo apt-get remove wireshark
   sudo apt purge wireshark-qt wireshark-gtk
exit
fi

# apache2
echo do you want to remove apache2 ? Y/N
read YN

if [ "$YN" = "y" ]; then 
  echo removing apache2
   sudo apt remove apache2*
exit
fi


#function  for software not in the script
uname() { 
echo give name of software to be removed
read softname
sudo apt-get remove --purge $softname
sudo apt-get remove $softname

echo do you want to remove more software? Y/N
read YN
if [ "$YN" = "y" ]; then 
uname
exit
fi
}

uname

sudo apt-get autoremove
sudo apt --purge autoremove
