#!/bin/bash
# RSR stands for RSR Software Remover
# Ensure the script is being run as root

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root."
   exit 1
fi
echo read read me 

# wire shark 
echo do you want to remove wire shark? Y/N
read YN

if [ "$YN" = "y" ]; then 
  echo removing wire shark
   sudo apt-get remove --purge wireshark
   sudo apt-get remove wireshark
exit
fi

sudo apt-get autoremove
