#!/bin/bash

# Get a list of all system users
users=$(cut -d: -f1 /etc/passwd)

# Function to manage individual users
manage_user() {
    user=$1
    echo -e "\nManaging user: $user"
    echo "What would you like to do with '$user'?"
    echo "1) Delete the user"
    echo "2) Give the user sudo privileges"
    echo "3) Revoke sudo privileges"
    echo "4) Force password change at next login"
    echo "5) Skip this user"
    read -p "Choose an option (1-5): " option

    case $option in
        1)
            sudo deluser --remove-home $user
            echo "User '$user' deleted."
            ;;
        2)
            sudo usermod -aG sudo $user
            echo "User '$user' added to sudo group."
            ;;
        3)
            sudo deluser $user sudo
            echo "User '$user' removed from sudo group."
            ;;
        4)
            sudo passwd -e $user
            echo "Password for user '$user' will be changed at next login."
            ;;
        5)
            echo "Skipping user '$user'."
            ;;
        *)
            echo "Invalid option. Skipping user '$user'."
            ;;
    esac
}

# Loop through all users and manage them
for user in $users; do
    # Skip system users
    if [ "$user" != "root" ] && id -u "$user" >/dev/null 2>&1 && [ "$(grep ^$user: /etc/passwd | cut -d: -f7)" != "/usr/sbin/nologin" ]; then
        manage_user $user
    fi
done

echo -e "\nUser management completed."
