#!/bin/bash

# Function to handle user choices
manage_user() {
    local username=$1
    echo "Managing user: $username"

    PS3="Choose an option for user '$username': "
    options=("Remove User" "Add to Sudo" "Force Password Reset" "Skip")
    select opt in "${options[@]}"; do
        case $REPLY in
            1)
                read -p "Are you sure you want to remove user '$username'? (y/n): " confirm
                if [[ "$confirm" == "y" ]]; then
                    sudo deluser --remove-home "$username"
                    echo "User '$username' removed from the system."
                else
                    echo "Aborted removal of '$username'."
                fi
                break
                ;;
            2)
                sudo usermod -aG sudo "$username"
                echo "User '$username' added to sudo group."
                break
                ;;
            3)
                sudo chage -d 0 "$username"
                echo "Password for user '$username' will need to be changed at next login."
                break
                ;;
            4)
                echo "Skipping user '$username'."
                break
                ;;
            *)
                echo "Invalid option. Please choose between 1-4."
                ;;
        esac
    done
    echo "----------------------------------------"
}

# Fetch all non-system users (UID >= 1000)
echo "Starting user management..."
while IFS=: read -r username _; do
    uid=$(id -u "$username" 2>/dev/null)
    if [[ "$uid" -ge 1000 ]]; then
        manage_user "$username"
    fi
done < /etc/passwd

echo "User management complete."
